name: child_personality_analysis
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  confetti: ^0.8.0
  flutter_animate: ^4.0.0
  flutter_svg: ^2.0.11
  flutter_screenutil: ^5.7.0
  flutter_staggered_grid_view: ^0.6.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  lottie: ^3.1.0
  flutter_markdown: ^0.6.18

  cupertino_icons: ^1.0.8
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatars/
    - assets/animations/
    - assets/icons/
    - lib/core/data/avatar_data.json

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
